#!/usr/local/bin/julia -q

arg = ARGS[1]
targetPath = joinpath(pwd(), arg)
targetFiles = readdir(targetPath)

for file in targetFiles
  shortcut = joinpath(homedir(), file)
  rm(shortcut, force = true, recursive = true)
  symlink(joinpath(targetPath, file), shortcut)
end
